apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./config/default
images:
- name: controller
  newName: ghcr.io/cert-manager/aws-privateca-issuer/controller
  newTag: v0.2.1-22-gc37adc0
